# @package model

id: claude-3-5-sonnet-20241022
name: "Claude 3.5 Sonnet (new)"
model_name: "claude-3-5-sonnet-20241022"
type: "anthropic"
system_prompt: "You are a helpful AI assistant that analyzes problems carefully and provides accurate answers."
temperature: 0.0 