# @package model

id: o1-mini-2024-09-12
name: "OpenAI o1-mini"
model_name: "o1-mini-2024-09-12"
type: "openai"
system_prompt: "You are a helpful AI assistant that analyzes problems carefully and provides accurate answers."
temperature: 1.0 