# @package model

id: o3-2025-04-16
name: "OpenAI o3"
model_name: "o3-2025-04-16"
type: "openai"
system_prompt: "You are a helpful AI assistant that analyzes problems carefully and provides accurate answers."
temperature: 1.0 