# @package model

id: o4-mini-2025-04-16
name: "OpenAI o4-mini"
model_name: "o4-mini-2025-04-16"
type: "openai"
system_prompt: "You are a helpful AI assistant that analyzes problems carefully and provides accurate answers."
temperature: 1.0 