# @package hydra.hydra_logging
# Custom hydra logging configuration that saves logs to .logs directory

version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
  colorlog:
    (): colorlog.ColoredFormatter
    format: '[%(asctime)s][%(name)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: .logs/hydra.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false